shell = "C:\\Program Files\\PowerShell\\7\\pwsh.exe -nologo"

import = [
  "C:\\Users\\Pierluigi\\AppData\\Roaming\\alacritty\\themes\\tokyo-night.toml"
]

working_directory = "C:\\Users\\Pierluigi"

[font]	
normal = { family = "MesloLGM Nerd Font" }

[window]
startup_mode = "Fullscreen"
padding = { x = 5, y = 5}

[keyboard]
bindings = [
    {key = "F11", action = "ToggleFullscreen"}
]
